title: Nick Shepherd
tagline: goodcodeguy
url: http://goodcodeguy.com
name: Good Code Guy
markdown: redcarpet
pygments: true
permalink: pretty

sass:
  style: expanded
  deploy_style: compressed

  compile_in_place: false